// Imports
import React from "react";
import Box from "@mui/material/Box";
import Menu from "@mui/material/Menu";
import Page from "../components/Page";
import MenuItem from "@mui/material/MenuItem";
import IconButton from "@mui/material/IconButton";
import { useTheme } from "@mui/material/styles";
import GlobalStyles from "@mui/material/GlobalStyles";
import AbstractTooltip from "../components/AbstractTooltip";
import DownloadIcon from "@mui/icons-material/FileDownloadOutlined";
import ResumeDocument from "../components/resume/ResumeDocument";
import { resumeScreenSx } from "../components/resume/screenStyles";

// Constants
// Generated by `npm run resume:pdf` into public/, so the URLs are stable
const DOWNLOADS = [
  { label: "Styled PDF", file: "James-Easter-Resume.pdf" },
  { label: "ATS version", file: "James-Easter-Resume-ATS.pdf" },
];

// Cmd+P on /resume should yield the resume, not the surrounding app chrome
const PRINT_STYLES = {
  "@media print": {
    '[data-print="hide"]': { display: "none !important" },
    body: { background: "#fff" },
    ".resume": {
      maxWidth: "none",
      margin: 0,
      padding: 0,
      boxShadow: "none",
      background: "transparent",
    },
    ".resume-section, .resume-entry": { breakInside: "avoid" },
  },
};

/**
 * Resume Page
 */
const Resume: React.FC = () => {
  const theme = useTheme();
  const [anchor, setAnchor] = React.useState<HTMLElement | null>(null);
  const close = () => setAnchor(null);

  return (
    <>
      <GlobalStyles styles={PRINT_STYLES} />
      <Page
        sx={{
          // m: 3 keeps the title aligned with the other pages
          m: 3,
          mx: "auto",
          px: { xs: 2, sm: 3 },
          maxWidth: 960,
          // Override the fixed viewport height so the resume scrolls naturally
          height: "auto",
        }}
        action={
          <>
            <AbstractTooltip title="Download" placement="right">
              <IconButton
                data-print="hide"
                aria-haspopup="menu"
                aria-label="Download resume"
                onClick={(event) => setAnchor(event.currentTarget)}
                // p: 0 keeps the button within the title's line height
                sx={{ p: 0, ml: 1 }}
              >
                <DownloadIcon fontSize="small" />
              </IconButton>
            </AbstractTooltip>
            {/* The styled PDF leads; the ATS one is for upload forms */}
            <Menu anchorEl={anchor} open={Boolean(anchor)} onClose={close}>
              {DOWNLOADS.map(({ label, file }) => (
                <MenuItem
                  key={file}
                  href={`/${file}`}
                  download={file}
                  onClick={close}
                  component="a"
                >
                  {label}
                </MenuItem>
              ))}
            </Menu>
          </>
        }
      >
        <Box sx={resumeScreenSx(theme)}>
          <ResumeDocument variant="screen" />
        </Box>
      </Page>
    </>
  );
};

export default Resume;
